version: "3.9"
services:
  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    networks:
      - internal
      - external

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: frontend
    working_dir: /frontend
    environment:
      VITE_PORT: ${VITE_PORT}
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    command: sh -c "npm run dev"
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    networks:
      - internal

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: api
    working_dir: /api
    environment:
      PORT: ${PORT}
    volumes:
      - ./api:/api
      - /api/node_modules
    command: sh -c "npm run dev"
    ports:
      - ${PORT}:${PORT}
    networks:
      - internal

networks:
  external:
    internal: false
  internal:
    internal: true
