//@deprecated

import { googleClient } from "./client";
import { IDENTITY_CONFIG } from "../utils/config";

/**
 * Function to authorize user
 * https://developers.google.com/identity/openid-connect/openid-connect#authenticationuriparameters
 *
 * nonce(string): Random value generated by app for replay protection
 * @returns
 */
export const authorize = async () => {
  return googleClient
    .get(IDENTITY_CONFIG.authority, {
      params: {
        client_id: IDENTITY_CONFIG.client_id,
        nonce: (Math.random() + 1).toString(36).substring(7),
        response_type: IDENTITY_CONFIG.response_type,
        redirect_uri: "http://localhost:3000/",
        scope: IDENTITY_CONFIG.scope,
      },
    })
    .then((res) => res);
};
